#!/usr/bin/env python3
"""Build a design's public Chat-history transcript (conversation.jsonl).

The platform shows a design's chat history from a `conversation.jsonl` at the
project snapshot root, in Claude Code session-JSONL shape (contract pinned in
panda-social-backend services/import_extract.go: importConversationName +
sampleSessionJSONL; the FE reuses its transcript renderer on it). Our publish
never shipped one, so pipeline designs had an empty chat page (found on
Trotter, 2026-08-24).

This builds a CLEAN synthesized conversation - the design prompt as the user
turn, then one assistant turn per pipeline round (each round's final summary:
the `.codex_<tag>.txt` / `.claude_<tag>.txt` files) with the files' real
mtimes as timestamps. Deliberately NOT the raw agent rollouts: those are tens
of MB of tool-call events in a schema the FE renderer doesn't know.

    ./conversation_jsonl.py <out_dir> [--rounds-dir DIR ...] [--prompt TEXT]
                            [--sub PATTERN=REPL ...] [--force]

Prompt source: --prompt, else <out_dir>/run.json "prompt", else the first
prose of seed.md / brief.md. --sub applies a case-insensitive regex
substitution to EVERYTHING published (prompt and summaries) - e.g. scrubbing
a trademarked reference name. Absolute /root/... paths are always reduced to
their basename: box internals never belong in a public transcript.

Writes <out_dir>/conversation.jsonl. gcs_upload_project.py ships any
conversation.jsonl sitting beside the STL and lists it in _tree.json, so
callers only need to build the file before the project upload.
"""
import glob
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROUND_CAP = 6000          # chars per assistant turn - summaries, not dumps
MAX_BYTES = 20 << 20      # sanity cap, far under the platform's ~100MB limit


def iso(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def scrub(text: str, subs) -> str:
    # Box paths -> basename first, then the caller's substitutions.
    text = re.sub(r"/root/[^\s)\]'\"]+", lambda m: m.group(0).rstrip("/").rsplit("/", 1)[-1], text)
    for pat, repl in subs:
        text = re.sub(pat, repl, text, flags=re.I)
    return text


def find_prompt(out_dir: Path, explicit: str) -> str:
    if explicit:
        return explicit
    rj = out_dir / "run.json"
    if rj.is_file():
        try:
            p = json.loads(rj.read_text(encoding="utf-8")).get("prompt", "")
            if p:
                return p
        except Exception:  # noqa: BLE001
            pass
    for name in ("seed.md", "brief.md"):
        f = out_dir / name
        if f.is_file():
            prose = re.sub(r"```.*?```", "", f.read_text(encoding="utf-8"), flags=re.S)
            lines = [ln.strip() for ln in prose.splitlines()
                     if ln.strip() and not ln.strip().startswith("#")]
            if lines:
                return " ".join(lines)[:600]
    return ""


def round_files(dirs):
    files = []
    for d in dirs:
        for pat in (".codex_*.txt", ".claude_*.txt"):
            files += [Path(p) for p in glob.glob(str(Path(d) / pat))]
    files = [f for f in files if f.is_file() and f.stat().st_size >= 20]
    return sorted(files, key=lambda f: f.stat().st_mtime)


def tag_of(f: Path) -> str:
    return re.sub(r"^\.(codex|claude)_", "", f.stem)


def build(out_dir: Path, rounds_dirs, prompt: str, subs, force: bool) -> Path:
    dst = out_dir / "conversation.jsonl"
    if dst.is_file() and not force:
        print(f"conversation.jsonl already exists ({dst.stat().st_size} bytes) - use --force")
        return dst
    files = round_files(rounds_dirs or [out_dir])
    prompt = scrub(find_prompt(out_dir, prompt).strip(), subs)
    if not prompt:
        sys.exit("no prompt found (run.json/seed.md/brief.md) and none given")

    t0 = (files[0].stat().st_mtime - 60) if files else out_dir.stat().st_mtime
    lines = [{"type": "user",
              "message": {"role": "user", "content": prompt},
              "timestamp": iso(t0)}]
    for f in files:
        text = scrub(f.read_text(encoding="utf-8", errors="replace").strip(), subs)
        if len(text) > ROUND_CAP:
            text = text[:ROUND_CAP] + "\n[...]"
        lines.append({"type": "assistant",
                      "message": {"role": "assistant",
                                  "content": [{"type": "text",
                                               "text": f"[{tag_of(f)}]\n{text}"}]},
                      "timestamp": iso(f.stat().st_mtime)})
    if len(lines) == 1:
        lines.append({"type": "assistant",
                      "message": {"role": "assistant",
                                  "content": [{"type": "text",
                                               "text": "Design generated by the automated pipeline; "
                                                       "round summaries were not retained for this run."}]},
                      "timestamp": iso(t0 + 60)})
    body = "\n".join(json.dumps(l, ensure_ascii=False) for l in lines) + "\n"
    if len(body.encode()) > MAX_BYTES:
        sys.exit(f"transcript would be {len(body) >> 20}MB - refusing (cap {MAX_BYTES >> 20}MB)")
    dst.write_text(body, encoding="utf-8")
    print(f"wrote {dst} ({len(lines)} turns, {len(body)} bytes)")
    return dst


def main() -> int:
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return 2
    out_dir = Path(args[0]).resolve()
    if not out_dir.is_dir():
        sys.exit(f"no such dir: {out_dir}")
    rounds, subs, prompt, force = [], [], "", "--force" in args
    i = 1
    while i < len(args):
        a = args[i]
        if a == "--rounds-dir":
            i += 1
            rounds.append(args[i])
        elif a == "--prompt":
            i += 1
            prompt = args[i]
        elif a == "--sub":
            i += 1
            pat, _, repl = args[i].partition("=")
            subs.append((pat, repl))
        i += 1
    build(out_dir, rounds, prompt, subs, force)
    return 0


if __name__ == "__main__":
    sys.exit(main())
